services:
  bot:
    container_name: bot
    image: ghcr.io/lagrangedev/lagrange.onebot:edge
    restart: always
    volumes:
      - ./bot:/app/data
      - ./ws:/ws
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - ws
    networks:
      - my_network
  ws:
    build: .
    container_name: jxh-bot-ws
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - my_network
    depends_on:
      - quote

  quote:
    image: zhullyb/qq-quote-generator
    container_name: qq-quote-generator
    ports:
      - "5004:5000"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
