services:
  bot:
    container_name: bot
    image: ghcr.io/lagrangedev/lagrange.onebot:edge
    restart: always
    volumes:
      - ./bot:/app/data
      - ./ws:/ws
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - ws
    networks:
      - my_network

  ws:
    image: python:3.12-slim
    command: >
      bash -c "pip install --upgrade pip &&
               pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt &&
               python server.py"
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./ws:/app
    depends_on:
      - quote
    networks:
      - my_network

  quote:
    image: zhullyb/qq-quote-generator
    container_name: qq-quote-generator
    ports:
      - "5004:5000"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
