version: '3.8'

services:
  bot:
    container_name: bot
    image: ghcr.io/lagrangedev/lagrange.onebot:edge
    restart: always
    volumes:
      - ./bot:/app/data
      - ./ws:/ws
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - ws
    networks:
      - my_network

  ws:
    image: python:3.12-slim
    command: >
      bash -c "pip install --upgrade pip &&
               pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt &&
               python server.py"
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./ws:/app
    depends_on:
      - quote
    networks:
      - my_network
  # rag:
  #   container_name: rag
  #   image: python:3.12-slim
  #   restart: always
  #   command: >
  #     bash -c "pip install --upgrade pip &&
  #              pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt &&
  #              python RAG-qwen.py"
  #   working_dir: /app
  #   volumes:
  #     - ./SimpleRAG:/app
  #   ports:
  #     - "5005:5005"
  #   depends_on:
  #     - qwen-free-api
  #   networks:
  #     - my_network

  # qwen-free-api:
  #   container_name: qwen-free-api
  #   image: vinlic/qwen-free-api:latest
  #   restart: always
  #   ports:
  #     - "5003:8000"
  #   environment:
  #     - TZ=Asia/Shanghai
  #   networks:
  #     - my_network

  # quote:
  #   container_name: quote-generator
  #   build:
  #     context: ./qq-quote-generator
  #     dockerfile: Dockerfile
  #   restart: always
  #   working_dir: /app
  #   ports:
  #     - "5004:5000"
  #   volumes:
  #     - ./qq-quote-generator:/app
  #   networks:
  #     - my_network

  quote:
    image: qq-quote:v2
    restart: always
    working_dir: /app
    ports:
      - "5004:5000"
    volumes:
      - ./qq-quote-generator:/app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
